## Text Data

In [18]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('attention')
df.head()

   Unnamed: 0  subject attention  solutions  score
0           0        1   divided          1    2.0
1           1        2   divided          1    3.0
2           2        3   divided          1    3.0
3           3        4   divided          1    5.0
4           4        5   divided          1    4.0

In [20]:
df.attention.unique()

array(['divided', 'focused'], dtype=object)

In [22]:
pd.get_dummies(df, columns=['attention']).head()

   Unnamed: 0  subject  solutions  score  attention_divided  attention_focused
0           0        1          1    2.0               True              False
1           1        2          1    3.0               True              False
2           2        3          1    3.0               True              False
3           3        4          1    5.0               True              False
4           4        5          1    4.0               True              False

In [44]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
lb = LabelBinarizer()
oe = OneHotEncoder()
x = lb.fit_transform(df.attention.to_numpy())
oe.fit_transform(x)[0].toarray()

array([[1., 0.]])

## Tokenizer

In [2]:
from nltk.tokenize import word_tokenize

text = "This is a test from rezvan course!"
word_tokenize(text)

['This', 'is', 'a', 'test', 'from', 'rezvan', 'course', '!']

In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")
text = "This is a test from rezvan course!"
docs = nlp(text)
[token for token in docs]

[This, is, a, test, from, rezvan, course, !]

In [61]:
from hazm import word_tokenize

text = "این یک متن فارسی برای تست است از رویداد رضوان."
tokens = word_tokenize(text)
tokens

['این',
 'یک',
 'متن',
 'فارسی',
 'برای',
 'تست',
 'است',
 'از',
 'رویداد',
 'رضوان',
 '.']

In [8]:
from textblob import TextBlob

text = "این یک متن فارسی برای تست است از رویداد رضوان."
blob = TextBlob(text)
blob.words

WordList(['این', 'یک', 'متن', 'فارسی', 'برای', 'تست', 'است', 'از', 'رویداد', 'رضوان'])

In [62]:
tokens = [token.lower() for token in tokens]
tokens

['این',
 'یک',
 'متن',
 'فارسی',
 'برای',
 'تست',
 'است',
 'از',
 'رویداد',
 'رضوان',
 '.']

In [63]:
tokens = [token.strip() for token in tokens]
tokens

['این',
 'یک',
 'متن',
 'فارسی',
 'برای',
 'تست',
 'است',
 'از',
 'رویداد',
 'رضوان',
 '.']

In [64]:
tokens = [token for token in tokens if not token.isdigit()]
tokens

['این',
 'یک',
 'متن',
 'فارسی',
 'برای',
 'تست',
 'است',
 'از',
 'رویداد',
 'رضوان',
 '.']

## Removing Punctuations and Stop words

In [73]:
from nltk.corpus import stopwords

# nltk.load()
text = "This is a test from rezvan course!"
tokens = word_tokenize(text)
stopword_list = stopwords.words('english')
[token for token in tokens if token not in stopword_list]

['This', 'test', 'rezvan', 'course', '!']

In [74]:
import string

punc = string.punctuation
[token for token in tokens if token not in punc]

['This', 'is', 'a', 'test', 'from', 'rezvan', 'course']

## Lemmatization and stemming

In [29]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
from nltk.tokenize import word_tokenize

text_str = "Artificial intelligence (AI) is a branch of computer science that aims to build machines capable of performing tasks that typically require human intelligence. AI enables machines to simulate human abilities, such as learning, problem-solving, decision-making and comprehension. Common applications of AI include speech recognition, image recognition, content generation, recommendation systems and self-driving cars."
text = word_tokenize(text_str)
lem = WordNetLemmatizer()
lem_ = [lem.lemmatize(token) for token in text]
porterstem = PorterStemmer()
porterstem_ = [porterstem.stem(token) for token in text]
snowstem = SnowballStemmer('english')
snowstem_ = [snowstem.stem(token) for token in text]
' '.join(text), ' '.join(lem_), ' '.join(porterstem_), ' '.join(snowstem_)

('Artificial intelligence ( AI ) is a branch of computer science that aims to build machines capable of performing tasks that typically require human intelligence . AI enables machines to simulate human abilities , such as learning , problem-solving , decision-making and comprehension . Common applications of AI include speech recognition , image recognition , content generation , recommendation systems and self-driving cars .',
 'Artificial intelligence ( AI ) is a branch of computer science that aim to build machine capable of performing task that typically require human intelligence . AI enables machine to simulate human ability , such a learning , problem-solving , decision-making and comprehension . Common application of AI include speech recognition , image recognition , content generation , recommendation system and self-driving car .',
 'artifici intellig ( ai ) is a branch of comput scienc that aim to build machin capabl of perform task that typic requir human intellig . ai enabl machin to simul human abil , such as learn , problem-solv , decision-mak and comprehens . common applic of ai includ speech recognit , imag recognit , content gener , recommend system and self-driv car .',
 'artifici intellig ( ai ) is a branch of comput scienc that aim to build machin capabl of perform task that typic requir human intellig . ai enabl machin to simul human abil , such as learn , problem-solv , decision-mak and comprehens . common applic of ai includ speech recognit , imag recognit , content generat , recommend system and self-driv car .')

In [30]:
from textblob import TextBlob
wiki = TextBlob(text_str)
words = wiki.tokenize()
words.lemmatize()

WordList(['Artificial', 'intelligence', '(', 'AI', ')', 'is', 'a', 'branch', 'of', 'computer', 'science', 'that', 'aim', 'to', 'build', 'machine', 'capable', 'of', 'performing', 'task', 'that', 'typically', 'require', 'human', 'intelligence', '.', 'AI', 'enables', 'machine', 'to', 'simulate', 'human', 'ability', ',', 'such', 'a', 'learning', ',', 'problem-solving', ',', 'decision-making', 'and', 'comprehension', '.', 'Common', 'application', 'of', 'AI', 'include', 'speech', 'recognition', ',', 'image', 'recognition', ',', 'content', 'generation', ',', 'recommendation', 'system', 'and', 'self-driving', 'car', '.'])

In [31]:
from textblob import TextBlob
wiki = TextBlob(text_str)
words = wiki.tokenize()
words.stem()

WordList(['artifici', 'intellig', '(', 'ai', ')', 'is', 'a', 'branch', 'of', 'comput', 'scienc', 'that', 'aim', 'to', 'build', 'machin', 'capabl', 'of', 'perform', 'task', 'that', 'typic', 'requir', 'human', 'intellig', '.', 'ai', 'enabl', 'machin', 'to', 'simul', 'human', 'abil', ',', 'such', 'as', 'learn', ',', 'problem-solv', ',', 'decision-mak', 'and', 'comprehens', '.', 'common', 'applic', 'of', 'ai', 'includ', 'speech', 'recognit', ',', 'imag', 'recognit', ',', 'content', 'gener', ',', 'recommend', 'system', 'and', 'self-driv', 'car', '.'])

In [42]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(text_str)

' '.join([token.lemma_ for token in doc])

'artificial intelligence ( AI ) be a branch of computer science that aim to build machine capable of perform task that typically require human intelligence . AI enable machine to simulate human ability , such as learning , problem - solve , decision - making and comprehension . common application of AI include speech recognition , image recognition , content generation , recommendation system and self - drive car .'

In [37]:
from hazm import word_tokenize, Lemmatizer, Stemmer

text = 'خدا زمین رو گرد آفرید تا به انسان بگه همون لحظه ای که فکر می کنی به آخر دنیا رسیده ای درست در نقطه آغاز هستی'
tokens = word_tokenize(text)
lemmatizer = Lemmatizer()
' '.join([lemmatizer.lemmatize(token) for token in tokens])

'خدا زمین رو گرد آفرید تا به انسان بگه همون لحظه ای که فکر می کرد#کن به آخر دنیا رسید#رس درست در نقطه آغاز هستی'

In [38]:
from hazm import word_tokenize, Lemmatizer, Stemmer

text = 'خدا زمین رو گرد آفرید تا به انسان بگه همون لحظه ای که فکر می کنی به آخر دنیا رسیده ای درست در نقطه آغاز هستی'
tokens = word_tokenize(text)
stemmer = Stemmer()
' '.join([stemmer.stem(token) for token in tokens])

'خدا زمین رو گرد آفرید تا به انس بگه همون لحظه ا که فکر م کن به آخر دنیا رسیده_ا درس در نقطه آغاز هست'

## POS Tagging

In [2]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "This is a test from rezvan course!"
docs = nlp(text)
[token.pos_ for token in docs]

['PRON', 'AUX', 'DET', 'NOUN', 'ADP', 'ADJ', 'NOUN', 'PUNCT']

In [17]:
import nltk
from nltk import tag
from nltk.tokenize import word_tokenize

nltk.download('averaged_perceptron_tagger_eng')

text = "This is a test from rezvan course!"
words = word_tokenize(text)
tag.pos_tag(words)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/aliakbar/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

[('This', 'DT'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('test', 'NN'),
 ('from', 'IN'),
 ('rezvan', 'JJ'),
 ('course', 'NN'),
 ('!', '.')]

In [6]:
import hazm

text = 'خدا زمین رو گرد آفرید تا به انسان بگه همون لحظه ای که فکر می کنی به آخر دنیا رسیده ای درست در نقطه آغاز هستی'
words = hazm.word_tokenize(text)
tagger = hazm.POSTagger ( model = 'pos_tagger.model' )
tagger.tag (words)

[('خدا', 'NOUN'),
 ('زمین', 'NOUN'),
 ('رو', 'ADP'),
 ('گرد', 'NOUN'),
 ('آفرید', 'VERB'),
 ('تا', 'SCONJ'),
 ('به', 'ADP'),
 ('انسان', 'NOUN'),
 ('بگه', 'VERB'),
 ('همون', 'DET'),
 ('لحظه', 'NOUN'),
 ('ای', 'INTJ'),
 ('که', 'SCONJ'),
 ('فکر', 'NOUN'),
 ('می', 'NOUN'),
 ('کنی', 'VERB'),
 ('به', 'ADP'),
 ('آخر', 'ADJ,EZ'),
 ('دنیا', 'NOUN'),
 ('رسیده_ای', 'NOUN,EZ'),
 ('درست', 'ADJ'),
 ('در', 'ADP'),
 ('نقطه', 'NOUN,EZ'),
 ('آغاز', 'NOUN,EZ'),
 ('هستی', 'NOUN')]

## NER Tagging

In [13]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "This is a test from rezvan course!"
docs = nlp(text)
[token.ent_iob_ for token in docs]

['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']